- hosts: back
  become: yes
  become_user: root
  become_method: sudo

  tasks: 
    - name: get information on app back container
      docker_container_info: 
        name: appBack #nombre del contenedor que queremos mirar
      register: result #guarda el resultado del contendor

    - name: Does container exists?
      ansible_builtin.debug: 
        msg: "The container {{ 'exists' if result.exists else 'doesn't exist' }}"
      
    - name: Stop container
      docker_container:
        name: appBack
        state: stopped
      when: result.exists

    - name: Remove container
      docker_container:
        name: appBack
        state: absent
    
    - name: Remove image
      docker_image:
        name: appBack
        state: absent

    - name: Execute docker container
      docker_container: 
        name: appBack
        image: douglaslopezmena/backend
        state: started
        pull: true
        published_ports:
          - "8089:8089"
        env: #variables de entorno del back
          DATABASE_URL: '{{ database_url }}' #esta variable se pasa cuando llamemos al playbook con -e
