- import_playbook: all.yml
- hosts: db
  become: yes
  become_user: root
  become_method: sudo

  tasks: 
    - name: get information on database container
      docker_container_info: 
        name: apachedb #nombre del contenedor que queremos mirar
        debug: true #guarda el resultado del contendor
      
#   - name: Stop container
#     docker_container:
#       name: appDatabase
#       state: stopped
#     when: result.exists

#   - name: Remove container
#     docker_container:
#       name: appDatabase
#       state: absent
    
    - name: Execute docker container
      docker_container: 
        name: apachedb
        image: couchdb
        state: started
        pull: true
        debug: true
        published_ports:
          - "5984:5984"
        env:
          COUCHDB_USER: '{{ user }}'
          COUCHDB_PASSWORD: '{{ password }}'