- hosts: jk
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install OpenJDK
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes
    - name: ensure the jenkins apt repository key is installed
      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present

    - name: ensure the repository is configured
      apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes

    - name: ensure jenkins is running
      service: name=jenkins state=started