node {
  def CIPipeline

  step([$class: 'WsCleanup'])
  
  stage("Checkout code"){
    checkout scm
  }

  try {
    stage("Run test"){
      dir('frontend') {
        docker.image('node:10.11.0-alpine').inside {
          withEnv([
            /* Override the npm cache directory to avoid: EACCES: permission denied, mkdir '/.npm' */
            'npm_config_cache=npm-cache',
            /* Override HOME Path */
            'HOME=.'
          ]) {
            sh 'npm install'
            sh 'npm test'
          }
        }
      }
    }
  } catch (e) {

  } finally {
    junit '**/frontend/test-results.xml'
  }
  

  stage("Build frontend image"){
    dir('frontend') {
      frontendImage = docker.build('douglaslopezmena/frontend')
    }
  }

  stage("Pushing image to registry"){
    docker.withRegistry('', 'docker-hub') {
      frontendImage.push('$BUILD_NUMBER')
    }
  }

  stage("Removing unnecessary images"){
    sh 'docker image prune -a -f --filter "label!=douglaslopezmena/frontend"'
  }

  stage("Trigger CD") {
    build job: 'CD', parameters: [
      string(name: 'TAG', value: "$BUILD_NUMBER")
    ]
  }

}